services:
  - type: web
    name: bookmyshow-web
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
    startCommand: >
      python manage.py migrate &&
      python manage.py shell < create_admin.py &&
      gunicorn bookmyseat.wsgi:application
    staticPublishPath: staticfiles
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: bookmyseat.settings
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: PYTHON_VERSION
        value: "3.9"
      - key: RENDER
        value: "True"
      - key: DATABASE_URL
        value: postgresql://django_bookmyshow_user:uF7eu2GnnDbqvUgYswCYpIS5TKTtsAUS@dpg-cshi84o8fa8c739dsme0-a.oregon-postgres.render.com/django_bookmyshow
