# Generated by Django 3.2.19 on 2025-06-20 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='theater',
            name='base_price',
            field=models.DecimalField(decimal_places=2, default=200.0, max_digits=6),
        ),
    ]
